castai:
  apiKey: "49ba8e95da5a34bb75b4f6d432d1aa75ce1bf27d26eaa5115fa707182c89c3b0"
  clusterID: ""
  clusterIdSecretKeyRef:
    name: "castai-cluster-id"
    key: "CLUSTER_ID"
autoscaling:
  enabled: true